// Catálogo pré-cadastrado. É sincronizado a cada início (por nome): cria o que falta e corrige a classificação
// muscular e os textos do que já existe, para que uma correção aqui chegue a quem já tem o exercício na biblioteca.
// Exercícios do usuário (is_custom = true) nunca são tocados por essa sincronização.
//
// Classificação em três categorias (anatomia e biomecânica):
//  • primary: motor principal do movimento (o músculo cuja ação articular define o exercício).
//  • secondary: participa ativamente do movimento, mas não é o principal responsável pela força.
//  • stabilizer: não move a articulação-alvo; segura postura, tronco ou escápula durante a execução.
// Variações do mesmo exercício (ângulo do banco, inclinação do tronco etc.) podem mudar essa classificação —
// isso é comentado nas dicas de cada exercício quando relevante, em vez de criar entradas separadas.
import type { Equipment, Muscle } from '../../domain/gym';

export interface CatalogItem { name: string; primary: Muscle[]; secondary: Muscle[]; stabilizer: Muscle[]; equipment: Equipment; instructions: string; tips: string }
const x = (name: string, primary: Muscle[], secondary: Muscle[], stabilizer: Muscle[], equipment: Equipment, instructions: string, tips: string): CatalogItem =>
  ({ name, primary, secondary, stabilizer, equipment, instructions, tips });

export const CATALOG: CatalogItem[] = [
  // Peito ---------------------------------------------------------------------------------------------------
  x('Supino reto com barra', ['pectoral_major'], ['triceps_brachii', 'deltoid_anterior'], ['serratus_anterior', 'rotator_cuff'], 'barbell',
    'Deitado no banco, com a barra alinhada à linha do peito, desça até tocar levemente o esterno e empurre até estender os cotovelos sem travá-los.',
    'Escápulas retraídas e firmes no banco; pés apoiados no chão; punhos alinhados com os antebraços.'),
  x('Supino inclinado com barra', ['pectoral_major'], ['deltoid_anterior', 'triceps_brachii'], ['serratus_anterior'], 'barbell',
    'No banco a 30–45°, desça a barra até a parte superior do peito e empurre em linha reta até estender os braços.',
    'Inclinações acima de 45° deslocam boa parte do trabalho para o deltoide anterior.'),
  x('Supino declinado', ['pectoral_major'], ['triceps_brachii'], ['deltoid_anterior', 'serratus_anterior'], 'barbell',
    'No banco declinado, desça a barra até a porção inferior do peito e empurre de volta até estender os cotovelos.',
    'Prenda bem os pés no suporte e peça ajuda para retirar e recolocar a barra com segurança.'),
  x('Supino reto com halteres', ['pectoral_major'], ['deltoid_anterior', 'triceps_brachii'], ['serratus_anterior', 'rotator_cuff'], 'dumbbell',
    'Deitado, desça os halteres ao lado do peito até sentir o alongamento e empurre para cima, aproximando levemente as mãos no topo.',
    'A maior amplitude dos halteres alonga mais o peitoral; desça de forma controlada.'),
  x('Supino inclinado com halteres', ['pectoral_major'], ['deltoid_anterior', 'triceps_brachii'], ['serratus_anterior'], 'dumbbell',
    'No banco a 30°, desça os halteres até a altura do peito e empurre em linha reta para cima.',
    'Cotovelos a cerca de 45° do tronco; evite abri-los totalmente a 90°.'),
  x('Crucifixo com halteres', ['pectoral_major'], ['deltoid_anterior'], ['biceps_brachii'], 'dumbbell',
    'Com os cotovelos levemente flexionados, abra os braços em arco até sentir o alongamento no peito e feche contraindo o peitoral.',
    'Mantenha a flexão do cotovelo constante durante todo o movimento; não desça além do conforto do ombro.'),
  x('Crossover na polia', ['pectoral_major'], ['deltoid_anterior'], ['serratus_anterior', 'obliques'], 'cable',
    'Em pé entre as polias, traga as mãos à frente do corpo em arco e retorne controlando a fase de alongamento.',
    'Incline o tronco levemente à frente e mantenha a tensão constante durante todo o percurso.'),
  x('Peck deck (voador)', ['pectoral_major'], ['deltoid_anterior'], [], 'machine',
    'Sentado, una os braços à frente do peito e retorne devagar até sentir o alongamento, sem soltar totalmente o peso.',
    'Ajuste o banco para as manoplas ficarem na altura do peito.'),
  x('Supino na máquina', ['pectoral_major'], ['triceps_brachii', 'deltoid_anterior'], [], 'machine',
    'Empurre as manoplas à frente até quase estender os cotovelos e retorne controlando o peso.',
    'Boa opção para treinar próximo da falha com segurança, sem exigir equilíbrio da barra.'),
  x('Flexão de braço', ['pectoral_major'], ['triceps_brachii', 'deltoid_anterior'], ['rectus_abdominis', 'obliques', 'transverse_abdominis', 'gluteus_maximus'], 'bodyweight',
    'Mãos na largura dos ombros, corpo alinhado da cabeça aos calcanhares; desça o peito até próximo do chão e empurre até estender os cotovelos.',
    'Contraia abdômen e glúteos para não deixar o quadril cair durante o movimento.'),
  x('Mergulho nas paralelas', ['pectoral_major'], ['triceps_brachii', 'deltoid_anterior'], ['serratus_anterior'], 'bodyweight',
    'Nas paralelas, incline o tronco à frente, desça até os ombros ficarem na altura dos cotovelos e empurre de volta à extensão.',
    'Quanto mais inclinado o tronco, mais o peitoral participa; na vertical, o foco muda para o tríceps.'),

  // Costas ---------------------------------------------------------------------------------------------------
  x('Barra fixa', ['latissimus_dorsi'], ['biceps_brachii', 'teres_major', 'rhomboids'], ['trapezius', 'rectus_abdominis'], 'bodyweight',
    'Pegada pronada, um pouco mais aberta que os ombros; puxe o corpo até o queixo ultrapassar a barra e desça controlando.',
    'Inicie o movimento levando as escápulas para baixo antes de flexionar os cotovelos.'),
  x('Barra fixa supinada', ['latissimus_dorsi'], ['biceps_brachii'], ['trapezius', 'rhomboids'], 'bodyweight',
    'Pegada supinada na largura dos ombros; puxe até o queixo passar a barra, usando a força do bíceps e das costas.',
    'Boa opção para quem ainda não tem força suficiente para a pegada pronada.'),
  x('Puxada na frente (pulldown)', ['latissimus_dorsi'], ['biceps_brachii', 'teres_major'], ['trapezius', 'rectus_abdominis'], 'cable',
    'Sentado, puxe a barra até a parte superior do peito levando os cotovelos para baixo e para trás, e retorne estendendo os braços.',
    'Evite jogar o tronco para trás ou usar impulso; a barra desce pela força das costas.'),
  x('Puxada triângulo', ['latissimus_dorsi'], ['biceps_brachii', 'rhomboids'], ['trapezius'], 'cable',
    'Com a pegada triângulo, puxe até o peito mantendo os cotovelos próximos ao corpo, e retorne alongando as costas.',
    'Junte as escápulas no final do movimento antes de soltar a fase de retorno.'),
  x('Remada curvada com barra', ['latissimus_dorsi'], ['rhomboids', 'trapezius', 'biceps_brachii'], ['erector_spinae', 'gluteus_maximus', 'hamstrings'], 'barbell',
    'Com o tronco inclinado à frente e a coluna neutra, puxe a barra em direção ao abdômen e desça controlando.',
    'Mantenha a coluna neutra durante todo o movimento, com os joelhos levemente flexionados.'),
  x('Remada unilateral com halter', ['latissimus_dorsi'], ['rhomboids', 'biceps_brachii'], ['erector_spinae', 'obliques'], 'dumbbell',
    'Com uma mão e um joelho apoiados no banco, puxe o halter em direção ao quadril, levando o cotovelo para trás.',
    'Imagine levar o cotovelo ao quadril, não a mão ao ombro, para manter o foco nas costas.'),
  x('Remada sentada na polia', ['latissimus_dorsi'], ['rhomboids', 'trapezius', 'biceps_brachii'], ['erector_spinae'], 'cable',
    'Sentado, puxe o triângulo até o abdômen mantendo o tronco ereto, e retorne alongando as costas.',
    'Evite balançar o tronco para trás; o movimento é dos braços e das escápulas.'),
  x('Remada cavalinho', ['latissimus_dorsi'], ['rhomboids', 'biceps_brachii'], ['trapezius'], 'machine',
    'Com o peito apoiado, puxe as manoplas em direção à lateral do tronco e retorne controlando.',
    'O apoio no peito remove a exigência da lombar, permitindo focar só nas costas.'),
  x('Levantamento terra', ['erector_spinae', 'gluteus_maximus', 'hamstrings'], ['quadriceps', 'trapezius'], ['latissimus_dorsi', 'rectus_abdominis', 'obliques', 'brachioradialis'], 'barbell',
    'Com a barra rente às canelas, quadril para trás e coluna neutra, estenda quadril e joelhos ao mesmo tempo até ficar totalmente ereto, e desça pelo mesmo caminho.',
    'A barra desliza colada ao corpo o tempo todo; comece com cargas leves até dominar a técnica.'),
  x('Encolhimento com halteres', ['trapezius'], [], ['brachioradialis'], 'dumbbell',
    'Em pé, com os halteres ao lado do corpo, eleve os ombros em direção às orelhas e desça controlando.',
    'O movimento é reto, para cima e para baixo; evite girar os ombros.'),
  x('Pullover com halter', ['latissimus_dorsi'], ['pectoral_major', 'triceps_brachii'], ['rectus_abdominis'], 'dumbbell',
    'Deitado, com um halter segurado pelas duas mãos, leve-o em arco atrás da cabeça e retorne à frente do peito.',
    'Mantenha os cotovelos levemente flexionados e sinta o alongamento das costas antes de retornar.'),
  x('Hiperextensão lombar', ['erector_spinae'], ['gluteus_maximus', 'hamstrings'], ['rectus_abdominis'], 'bodyweight',
    'No banco romano, desça o tronco mantendo a coluna neutra e suba até alinhar tronco e pernas, sem hiperestender.',
    'Evite subir além da linha reta do corpo: o objetivo é fortalecer, não hiperestender a lombar.'),

  // Ombros ---------------------------------------------------------------------------------------------------
  x('Desenvolvimento com barra', ['deltoid_anterior'], ['deltoid_lateral', 'triceps_brachii'], ['trapezius', 'rectus_abdominis'], 'barbell',
    'Sentado ou em pé, empurre a barra da altura dos ombros até estender totalmente os braços acima da cabeça.',
    'Contraia abdômen e glúteos para não arquear a lombar durante o movimento.'),
  x('Desenvolvimento com halteres', ['deltoid_anterior'], ['deltoid_lateral', 'triceps_brachii'], ['trapezius', 'rotator_cuff'], 'dumbbell',
    'Empurre os halteres da altura das orelhas até quase se tocarem acima da cabeça, e desça controlando.',
    'Mantenha os antebraços na vertical durante toda a execução.'),
  x('Desenvolvimento Arnold', ['deltoid_anterior'], ['deltoid_lateral', 'triceps_brachii'], ['rotator_cuff', 'trapezius'], 'dumbbell',
    'Comece com as palmas voltadas para você; gire os punhos enquanto empurra os halteres para cima até estender os braços.',
    'Use uma carga menor que no desenvolvimento tradicional: a rotação exige mais controle.'),
  x('Elevação lateral', ['deltoid_lateral'], ['trapezius'], [], 'dumbbell',
    'Em pé, eleve os halteres pelas laterais até a altura dos ombros e desça devagar, sem usar impulso.',
    'Cotovelo levemente flexionado e polegar um pouco mais baixo que o mindinho; evite balançar o tronco.'),
  x('Elevação frontal', ['deltoid_anterior'], ['pectoral_major'], ['rectus_abdominis'], 'dumbbell',
    'Eleve o halter à frente do corpo até a altura dos ombros e desça controlando, sem balançar o tronco.',
    'Evite subir acima da linha dos ombros: isso reduz a tensão no deltoide e sobrecarrega a lombar.'),
  x('Crucifixo inverso', ['deltoid_posterior'], ['rhomboids', 'trapezius'], [], 'dumbbell',
    'Inclinado à frente, abra os braços em arco até a altura dos ombros, contraindo a parte de trás do ombro.',
    'Use carga leve e execução lenta: o deltoide posterior é pequeno e fácil de compensar com o tronco.'),
  x('Remada alta', ['deltoid_lateral'], ['trapezius', 'biceps_brachii'], [], 'barbell',
    'Puxe a barra rente ao corpo até a altura do peito, mantendo os cotovelos sempre acima das mãos.',
    'Uma pegada um pouco mais aberta que os ombros reduz o desconforto na articulação do ombro.'),
  x('Face pull', ['deltoid_posterior'], ['rotator_cuff', 'trapezius'], ['rhomboids'], 'cable',
    'Na polia alta com a corda, puxe em direção ao rosto abrindo os cotovelos e rodando os ombros para trás.',
    'Excelente para a saúde do ombro; use carga moderada e foque na rotação externa no final do movimento.'),

  // Bíceps ---------------------------------------------------------------------------------------------------
  x('Rosca direta com barra', ['biceps_brachii'], ['brachialis'], ['brachioradialis'], 'barbell',
    'Em pé, com os cotovelos fixos ao lado do corpo, flexione levando a barra até os ombros e desça controlando.',
    'Evite balançar o tronco para ajudar a subir a barra.'),
  x('Rosca alternada com halteres', ['biceps_brachii'], ['brachialis'], ['brachioradialis'], 'dumbbell',
    'Flexione um braço de cada vez, girando o punho para cima (supinação) ao longo do movimento.',
    'Desça completamente para alongar o bíceps antes da próxima repetição.'),
  x('Rosca martelo', ['brachialis'], ['brachioradialis'], ['biceps_brachii'], 'dumbbell',
    'Com as palmas voltadas uma para a outra, flexione os cotovelos sem girar o punho durante o movimento.',
    'Essa pegada neutra recruta bem o braquial e o braquiorradial, dando mais volume ao braço.'),
  x('Rosca Scott', ['biceps_brachii'], ['brachialis'], [], 'barbell',
    'Com os braços apoiados no banco Scott, flexione até a contração máxima e desça sem estender totalmente o cotovelo.',
    'Não trave o cotovelo no fim da descida: isso protege o tendão do bíceps.'),
  x('Rosca concentrada', ['biceps_brachii'], ['brachialis'], [], 'dumbbell',
    'Sentado, com o cotovelo apoiado na face interna da coxa, flexione o braço isolando o bíceps.',
    'Movimento lento, com foco na contração máxima no topo.'),
  x('Rosca na polia', ['biceps_brachii'], ['brachialis'], ['brachioradialis'], 'cable',
    'Na polia baixa, flexione os cotovelos mantendo tensão constante durante toda a repetição.',
    'A polia mantém a tensão mesmo com o braço estendido, diferente do halter.'),

  // Tríceps ---------------------------------------------------------------------------------------------------
  x('Tríceps testa', ['triceps_brachii'], [], [], 'barbell',
    'Deitado, com a barra W acima do peito, flexione os cotovelos levando-a em direção à testa e estenda de volta.',
    'Mantenha os cotovelos apontando para o teto e fixos durante todo o movimento.'),
  x('Tríceps na polia (corda)', ['triceps_brachii'], [], [], 'cable',
    'Em pé, com os cotovelos junto ao corpo, estenda os cotovelos empurrando a corda para baixo e abrindo as mãos no final.',
    'Não deixe os cotovelos se afastarem do tronco durante a execução.'),
  x('Tríceps francês', ['triceps_brachii'], [], [], 'dumbbell',
    'Com um halter segurado acima da cabeça, flexione os cotovelos atrás da nuca e estenda de volta.',
    'Cotovelos fechados e apontando para cima durante todo o movimento.'),
  x('Mergulho no banco', ['triceps_brachii'], ['deltoid_anterior'], ['pectoral_major'], 'bodyweight',
    'Com as mãos apoiadas no banco atrás do corpo, flexione os cotovelos descendo o quadril e empurre de volta à extensão.',
    'Não desça além de 90° nos cotovelos se sentir desconforto no ombro.'),
  x('Supino fechado', ['triceps_brachii'], ['pectoral_major'], ['deltoid_anterior'], 'barbell',
    'Supino com as mãos na largura dos ombros, cotovelos próximos ao tronco durante a descida e a subida.',
    'Não feche demais a pegada: isso pode sobrecarregar o punho.'),
  x('Tríceps coice', ['triceps_brachii'], [], ['deltoid_posterior'], 'dumbbell',
    'Com o tronco inclinado e o cotovelo fixo junto ao corpo, estenda o antebraço para trás até a extensão total.',
    'Use carga leve: o foco é a contração isolada do tríceps no final do movimento.'),

  // Antebraço ---------------------------------------------------------------------------------------------------
  x('Rosca de punho', ['wrist_flexors'], [], ['brachioradialis'], 'barbell',
    'Com os antebraços apoiados e as palmas para cima, flexione apenas os punhos, elevando a barra.',
    'Use amplitude completa e carga leve; o movimento é só do punho.'),
  x('Rosca inversa', ['wrist_extensors'], ['brachioradialis'], ['biceps_brachii'], 'barbell',
    'Com pegada pronada, flexione os cotovelos mantendo os punhos firmes e estendidos.',
    'Use uma carga bem menor que na rosca direta: os extensores do punho são mais fracos.'),

  // Pernas ---------------------------------------------------------------------------------------------------
  x('Agachamento livre', ['quadriceps', 'gluteus_maximus'], ['hamstrings'], ['erector_spinae', 'rectus_abdominis', 'obliques'], 'barbell',
    'Com a barra apoiada nas costas, desça flexionando quadril e joelhos até as coxas ficarem paralelas ao chão, e suba estendendo ambos.',
    'Joelhos alinhados com a direção dos pés e calcanhares sempre no chão.'),
  x('Agachamento frontal', ['quadriceps'], ['gluteus_maximus'], ['erector_spinae', 'rectus_abdominis'], 'barbell',
    'Com a barra apoiada na frente dos ombros, desça mantendo o tronco o mais ereto possível.',
    'Cotovelos altos durante todo o movimento para manter a barra estável.'),
  x('Leg press 45°', ['quadriceps'], ['gluteus_maximus'], ['hamstrings'], 'machine',
    'Empurre a plataforma estendendo os joelhos sem travá-los, e desça controlando até um ângulo confortável.',
    'Mantenha a lombar sempre apoiada; pés mais altos na plataforma enfatizam glúteos e posteriores.'),
  x('Hack squat', ['quadriceps'], ['gluteus_maximus'], [], 'machine',
    'Com as costas apoiadas, desça flexionando os joelhos e empurre a plataforma de volta à extensão.',
    'Pés mais baixos e próximos na plataforma aumentam o foco no quadríceps.'),
  x('Cadeira extensora', ['quadriceps'], [], [], 'machine',
    'Sentado, estenda os joelhos até a contração máxima e desça devagar, sem soltar o peso.',
    'Segure um instante no topo antes de descer, para maximizar a contração.'),
  x('Mesa flexora', ['hamstrings'], ['gastrocnemius'], [], 'machine',
    'Deitado, flexione os joelhos levando os calcanhares em direção aos glúteos, e estenda controlando.',
    'Mantenha o quadril colado ao banco durante todo o movimento.'),
  x('Stiff', ['hamstrings', 'gluteus_maximus'], ['erector_spinae'], ['brachioradialis'], 'barbell',
    'Com os joelhos levemente flexionados, incline o tronco levando o quadril para trás até sentir o alongamento posterior, e retorne à posição ereta.',
    'Mantenha a barra rente às pernas e a coluna neutra durante toda a execução.'),
  x('Afundo com halteres', ['quadriceps', 'gluteus_maximus'], ['hamstrings'], ['rectus_abdominis', 'obliques'], 'dumbbell',
    'Dê um passo à frente e desça até o joelho de trás quase tocar o chão, e volte empurrando com a perna da frente.',
    'Tronco ereto e passo longo o suficiente para o joelho da frente não ultrapassar muito a ponta do pé.'),
  x('Agachamento búlgaro', ['quadriceps', 'gluteus_maximus'], ['hamstrings'], ['gluteus_medius', 'rectus_abdominis'], 'dumbbell',
    'Com o pé de trás apoiado no banco, desça flexionando o joelho da frente e suba estendendo essa mesma perna.',
    'O equilíbrio é o maior desafio no início: comece com carga leve até se adaptar.'),
  x('Passada com halteres', ['quadriceps', 'gluteus_maximus'], ['hamstrings'], ['gastrocnemius', 'rectus_abdominis'], 'dumbbell',
    'Caminhe dando passos longos, descendo o joelho de trás a cada passada, alternando as pernas.',
    'Mantenha o tronco firme e o olhar à frente para ajudar no equilíbrio.'),
  x('Agachamento sumô', ['gluteus_maximus', 'hip_adductors'], ['quadriceps'], ['erector_spinae'], 'dumbbell',
    'Com os pés bem afastados e as pontas voltadas para fora, desça com um halter entre as pernas até as coxas ficarem paralelas ao chão.',
    'Os joelhos acompanham a direção dos pés durante toda a descida.'),
  x('Elevação pélvica (hip thrust)', ['gluteus_maximus'], ['hamstrings'], ['rectus_abdominis', 'erector_spinae'], 'barbell',
    'Com as costas apoiadas no banco e a barra sobre o quadril, eleve o quadril até alinhar tronco e coxas, contraindo os glúteos.',
    'Mantenha o queixo levemente recolhido e evite hiperestender a lombar no topo.'),
  x('Cadeira abdutora', ['gluteus_medius'], ['gluteus_maximus'], [], 'machine',
    'Sentado, abra as pernas contra a resistência da máquina e retorne devagar, controlando o movimento.',
    'Incline levemente o tronco à frente para aumentar o foco no glúteo médio.'),
  x('Kettlebell swing', ['gluteus_maximus', 'hamstrings'], ['erector_spinae'], ['rectus_abdominis', 'deltoid_anterior'], 'kettlebell',
    'Com o quadril liderando o movimento (dobradiça de quadril), empurre o kettlebell para trás entre as pernas e projete-o à frente até a altura do peito.',
    'O impulso vem da extensão explosiva do quadril, não dos braços puxando o peso.'),
  x('Panturrilha em pé', ['gastrocnemius'], ['soleus'], [], 'machine',
    'Em pé, suba nas pontas dos pés até a contração máxima e desça alongando totalmente a panturrilha.',
    'Faça uma pausa de um segundo em cima e embaixo para maximizar o trabalho muscular.'),
  x('Panturrilha sentado', ['soleus'], ['gastrocnemius'], [], 'machine',
    'Sentado, com o peso apoiado sobre os joelhos, eleve os calcanhares e desça devagar até o alongamento total.',
    'Com o joelho flexionado, o sóleo trabalha mais que o gastrocnêmio: use repetições mais altas.'),
  x('Panturrilha no leg press', ['gastrocnemius'], ['soleus'], [], 'machine',
    'Empurre a plataforma só com a ponta dos pés, mantendo os joelhos praticamente estendidos.',
    'Use amplitude completa em cada repetição para melhor resultado.'),

  // Abdômen ---------------------------------------------------------------------------------------------------
  x('Abdominal crunch', ['rectus_abdominis'], [], ['obliques'], 'bodyweight',
    'Deitado, com os joelhos flexionados, eleve os ombros do chão contraindo o abdômen, e desça controlando.',
    'Não puxe o pescoço com as mãos: a força vem do abdômen.'),
  x('Prancha', ['rectus_abdominis', 'transverse_abdominis'], ['obliques'], ['deltoid_anterior', 'gluteus_maximus', 'erector_spinae'], 'bodyweight',
    'Apoiado nos antebraços e nas pontas dos pés, mantenha o corpo alinhado da cabeça aos calcanhares, sem deixar o quadril subir ou cair.',
    'Contraia glúteos e abdômen ao mesmo tempo para manter a coluna estável durante todo o tempo.'),
  x('Elevação de pernas', ['rectus_abdominis'], ['hip_flexors'], ['obliques'], 'bodyweight',
    'Deitado ou pendurado, eleve as pernas retas até cerca de 90° e desça controlando, sem deixar a lombar arquear.',
    'Mantenha a lombar colada ao chão (ou a pelve neutra, se pendurado) durante todo o movimento.'),
  x('Abdominal na polia', ['rectus_abdominis'], ['obliques'], ['hip_flexors'], 'cable',
    'Ajoelhado, com a corda atrás da nuca, flexione o tronco levando os cotovelos em direção aos joelhos.',
    'O movimento parte da flexão da coluna, não do quadril puxando para trás.'),
  x('Abdominal com roda', ['rectus_abdominis'], ['transverse_abdominis', 'obliques'], ['latissimus_dorsi', 'deltoid_anterior', 'erector_spinae'], 'other',
    'De joelhos, role a roda à frente mantendo o abdômen contraído e a coluna neutra, e retorne puxando com o abdômen.',
    'Avance apenas até onde consegue manter a lombar estável, sem deixá-la afundar.'),
  x('Rotação russa', ['obliques'], ['rectus_abdominis'], ['hip_flexors'], 'bodyweight',
    'Sentado, com o tronco levemente inclinado para trás, gire de um lado para o outro tocando o chão ao lado do quadril.',
    'Segure um peso com as duas mãos para aumentar a exigência dos oblíquos.'),
];
